dbt_retail:
  outputs:
    dev:
      dataset: sales_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/service-account.json
      location: US
      method: service-account
      priority: interactive
      project: retail-project-430018
      threads: 4
      type: bigquery
  target: dev